### ISSUE TITLE
build on osx

### ISSUE THREAD

**Issue by jovo** [openconnectome/Rambo3D#1]
i tried to follow your instructions, but it failed to build, citing H5Cpp.h as missing.
when i put it in, it said that a whole bunch of other stuff was missing.
lil' help?

**Comment by mingchuang82** [comment]
Ah...I think that's for parsing h5 files, which I didn't have chance to
implement fully. I believe it's safe to comment it out.

Lemme look at it again tonight. My built was on an old machine which I left
at home.

--Ming

**Comment by jovo** [comment]
great, thanks minh!

On Tue, Apr 9, 2013 at 3:05 PM, mingchuang82 notifications@github.comwrote:

> Ah...I think that's for parsing h5 files, which I didn't have chance to
> implement fully. I believe it's safe to comment it out.
> 
> Lemme look at it again tonight. My built was on an old machine which I
> left
> at home.
> 
> --Ming
> 
> On Sun, Apr 7, 2013 at 8:44 AM, joshua vogelstein
> notifications@github.comwrote:
> 
> > i tried to follow your instructions, but it failed to build, citing
> > H5Cpp.h as missing.
> > when i put it in, it said that a whole bunch of other stuff was missing.
> > lil' help?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/openconnectome/Rambo3D/issues/1>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/openconnectome/Rambo3D/issues/1#issuecomment-16133281
> .

## 

If it makes you feel better, please remember to consider humanity before
doing stuff. in any case, i hope your day is filled with eudaimonia.
openconnecto.me, jovo.me

**Comment by jovo** [comment]
@ming - it'd be super awesome if we could resolve this in the immediate
future, as a paper is coming out next week that we'd like to show off our
everything with.
thanks, j

On Tue, Apr 9, 2013 at 8:33 PM, joshua vogelstein jovo@stat.duke.eduwrote:

> great, thanks minh!
> 
> On Tue, Apr 9, 2013 at 3:05 PM, mingchuang82 notifications@github.comwrote:
> 
> > Ah...I think that's for parsing h5 files, which I didn't have chance to
> > implement fully. I believe it's safe to comment it out.
> > 
> > Lemme look at it again tonight. My built was on an old machine which I
> > left
> > at home.
> > 
> > --Ming
> > 
> > On Sun, Apr 7, 2013 at 8:44 AM, joshua vogelstein
> > notifications@github.comwrote:
> > 
> > > i tried to follow your instructions, but it failed to build, citing
> > > H5Cpp.h as missing.
> > > when i put it in, it said that a whole bunch of other stuff was
> > > missing.
> > > lil' help?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/openconnectome/Rambo3D/issues/1>
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/openconnectome/Rambo3D/issues/1#issuecomment-16133281
> > .
> 
> ## 
> 
> If it makes you feel better, please remember to consider humanity before
> doing stuff. in any case, i hope your day is filled with eudaimonia.
> openconnecto.me, jovo.me

## 

If it makes you feel better, please remember to consider humanity before
doing stuff. in any case, i hope your day is filled with eudaimonia.
openconnecto.me, jovo.me
